### ISSUE TITLE
File Format

### ISSUE THREAD

**Issue by jblagden** [jblagden/rizzrack#1]
Creating a txt file formatted like
Date
InitialTimestamp - Activity
.
.
.
FinalTimestamp - Activity
Todo list:
Task - Status

That would make this readable outside of the program, and easy enough to emulate should you not have access to it.

**Comment by jblagden** [comment]
2016-12-31
10:00 - Start
12:00 - Stuff
14:00 - Most important stuff
18:00 - End
Todo list
Test app1 - complete
Test app1 - carriedover

**Comment by b-turchyn** [comment]
Thoughts on perhaps doing YAML for logging?

```yaml
- 2016-12-31
  - entry
    - start-time: 10:00
    - description: Start
  - entry
    - start-time: 12:00
    - description: Stuff
  - entry
    - start-time: 14:00
    - description: Most important
```

This has a few benefits:

- [Still easy to read](https://wiki.python.org/moin/YAML)
- There are already libraries to read the data
- If you want to add other, optional information at a later point, you can add entries in cleanly
